version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
       - MONGO_URI=mongodb://mongo:27017/ecommerce
       - JWT_SECRET=supersecretjwt
       - PORT=8000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:8000/api
    depends_on:
      - backend

volumes:
  mongo_data: